services:
  - type: web
    name: ailuma-auth-service
    plan: free
    env: node
    rootDir: backend/services/auth
    buildCommand: npm install --prefix ../../shared && npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false

  - type: web
    name: ailuma-chat-service
    plan: free
    env: node
    rootDir: backend/services/chat
    buildCommand: npm install --prefix ../../shared && npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        sync: false

  - type: web
    name: ailuma-agent-service
    plan: free
    env: node
    rootDir: backend/services/agent
    buildCommand: npm install --prefix ../../shared && npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false

  - type: web
    name: ailuma-billing-service
    plan: free
    env: node
    rootDir: backend/services/billing
    buildCommand: npm install --prefix ../../shared && npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: AUTH_SERVICE_HOSTPORT
        fromService:
          name: ailuma-auth-service
          type: web
          property: hostport

  - type: web
    name: ailuma-gateway
    plan: free
    env: node
    rootDir: backend/gateway
    buildCommand: npm install --prefix ../shared && npm install
    startCommand: npm start
    envVars:
      - key: REDIS_URL
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: AUTH_SERVICE_HOSTPORT
        fromService:
          name: ailuma-auth-service
          type: web
          property: hostport
      - key: CHAT_SERVICE_HOSTPORT
        fromService:
          name: ailuma-chat-service
          type: web
          property: hostport
      - key: AGENT_SERVICE_HOSTPORT
        fromService:
          name: ailuma-agent-service
          type: web
          property: hostport
      - key: BILLING_SERVICE_HOSTPORT
        fromService:
          name: ailuma-billing-service
          type: web
          property: hostport
