// React se zaroori hooks (useState) import kar rahe hain. 
// useState ka use component ka internal state track karne ke liye hota hai (e.g. kaunsa tab active hai).
import { useState } from "react";
import { useSelector } from "react-redux"; // Redux store se data (state) nikalne ke liye
import { motion, AnimatePresence } from "framer-motion"; // UI element me smooth animation add karne ke liye
// Icons import kar rahe hain lucide-react aur react-icons se (better UX ke liye)
import { X, Check, Copy, Code2, Eye, Share2, PanelRightClose, PanelRightOpen } from "lucide-react";
import { FiCode } from "react-icons/fi";
// Editor import kar rahe hain taaki code snippet properly VSCode jaisa dikhe
import Editor from "@monaco-editor/react";
// Custom helper function jo file extension ke base pe language detect karta hai (for syntax highlighting)
import { detectLanguage } from "../utils/detectLanguage";
// API helper backend me artifact share karne ke liye
import { shareArtifact } from "../features/chat.api";

// ArtifactPanel component mainly code generated by AI (artifact) ko right side panel me show karta hai.
export default function ArtifactPanel() {
  
  // States definition:
  // tab: Current active view track karne ke liye ("code" view hai ya "preview" view)
  const [tab, setTab] = useState("code");
  
  // activeFile: Agar multiple files generated hain, toh array ka index track karega ki kon si file khuli hai
  const [activeFile, setActiveFile] = useState(0);
  
  // collapsed: Panel collapse (chupana) hai ya open (expand) karna hai
  const [collapsed, setCollapsed] = useState(false);
  
  // mobileOpen: Mobile screens pe ye panel as a full screen drawer khulta hai, uska state
  const [mobileOpen, setMobileOpen] = useState(false);
  
  // copied: UX feedback ke liye (Copy click hone par thodi der checkmark dikhane ke liye)
  const [copied, setCopied] = useState(false);
  
  // shared: Link share hone ke baad "Copied!" feedback dikhane ke liye
  const [shared, setShared] = useState(false);

  // useSelector se 'message' slice (Redux store) me se artifacts nikal rahe hain.
  // Hum array ka pehla artifact lenge. Agar message naya aaya to state change hoga aur panel re-render hoga.
  const { artifacts } = useSelector(state => state.message);
  const artifact = artifacts?.[0];

  // Agar koi artifact nahi hai, toh ye component DOM me kuch render nahi karega (return null).
  if (!artifact) return null;

  // Artifact object me 'files' ka ek array hai. activeFile state ka use karke hum current file nikal rahe hain.
  const file = artifact?.files?.[activeFile];
  
  // 'preview' feature tabhi chalega jab HTML, CSS, aur JS files available hon.
  // Isliye find method ka use karke array me files verify kar rahe hain.
  const htmlFile = artifact?.files?.find(f => f.name === "index.html");
  const cssFile = artifact?.files?.find(f => f.name === "style.css");
  const jsFile = artifact?.files?.find(f => f.name === "script.js");
  
  // Agar htmlFile exist karti hai, toh Boolean() true dega, iska matlab app preview dikha sakti hai.
  const canPreview = Boolean(htmlFile);

  // iframe ke andar render karne ke liye fake HTML document (template literal se string) banaya.
  // Isme seedha CSS (style tag me) aur JS (script tag me) inject kiya gaya hai (Sandboxed preview technique).
  const previewDoc = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<style>${cssFile?.content || ""}</style>
</head>
<body>
${htmlFile?.content || ""}
<script>${jsFile?.content || ""}<\/script>
</body>
</html>`;

  // Code ko clipboard me copy karne ka function
  const handleCopy = () => {
    // navigator.clipboard Web API ka use code copy karne ke liye (Interview point)
    navigator.clipboard.writeText(file?.content || "");
    setCopied(true);
    // 2 seconds baad wapas 'Copy' text laane ke liye reset state
    setTimeout(() => setCopied(false), 2000);
  };

  // Artifact share karke ek unique link generate karne ka function
  const handleShare = async () => {
    try {
      // Backend ko data bheja. await ensure karega ki request puri hone ke baad hi next line chale.
      const data = await shareArtifact({ title: artifact.title, type: artifact.type, files: artifact.files });
      // Backend ek shareId dega jisko current website url (window.location.origin) me jod kar link bana li
      const url = `${window.location.origin}/shared/${data.shareId}`;
      
      // Link clipboard pe copy kar di
      await navigator.clipboard.writeText(url);
      setShared(true);
      setTimeout(() => setShared(false), 2000);
    } catch (error) {
      console.error("Failed to share artifact", error);
    }
  };

  // Ye component panel ka andar ka (main UI) content draw karega.
  // Nested component isliye banaya kyunki yahi same content Desktop Panel aur Mobile Drawer dono me use hoga. (Code Reusability - DRY Principle)
  const PanelContent = ({ onClose }) => (
    <div className="flex flex-col h-full bg-[#0d0f14]">

      {/* Header section: Jisme Close button, Title aur Share/Copy Actions honge */}
      <div className="h-14 px-4 border-b border-white/[0.06] flex items-center gap-3 shrink-0">
        
        {/* Close Button: agar mobile me hai toh onClose prop chalega, varna desktop panel collapse ho jayega */}
        <button
          onClick={onClose ?? (() => setCollapsed(true))}
          className="flex items-center justify-center w-7 h-7 rounded-lg text-slate-500 hover:text-slate-200 hover:bg-white/[0.05] transition-colors duration-150 bg-transparent border-none cursor-pointer shrink-0"
        >
          {onClose ? <X size={15} /> : <PanelRightClose size={15} />}
        </button>

        {/* Artifact Title Section */}
        <div className="flex items-center gap-2 flex-1 min-w-0">
          <div className="flex items-center justify-center w-6 h-6 rounded-md bg-indigo-500/10 border border-indigo-500/20 shrink-0">
            <FiCode className="text-indigo-400" size={12} />
          </div>
          <h2 className="text-[13px] font-medium text-slate-200 truncate">{artifact.title}</h2>
        </div>

        {/* Action Buttons Section */}
        <div className="flex items-center gap-1 shrink-0">
          {/* Share button */}
          <button
            onClick={handleShare}
            className="flex items-center gap-1.5 px-2.5 py-1.5 text-[11px] font-medium text-slate-400 hover:text-slate-200 hover:bg-white/[0.05] rounded-lg transition-colors duration-150 bg-transparent border-none cursor-pointer"
          >
            {shared ? <Check size={12} className="text-green-400" /> : <Share2 size={12} />}
            {shared ? "Link Copied!" : "Share"}
          </button>
          
          {/* Copy button: Sirf tabhi dikhega jab user "code" tab me hoga. Preview me code copy nahi kar sakte. (Conditional rendering) */}
          {tab === "code" && (
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-2.5 py-1.5 text-[11px] font-medium text-slate-400 hover:text-slate-200 hover:bg-white/[0.05] rounded-lg transition-colors duration-150 bg-transparent border-none cursor-pointer"
            >
              {copied ? <Check size={12} className="text-green-400" /> : <Copy size={12} />}
              {copied ? "Copied" : "Copy"}
            </button>
          )}

          {/* Toggle buttons: "Code" and "Preview". Sirf tabhi ayenge jab canPreview true ho */}
          {canPreview && (
            <div className="flex items-center gap-1 bg-white/[0.04] border border-white/[0.06] p-1 rounded-lg">
              <button
                onClick={() => setTab("code")}
                className={`flex items-center gap-1.5 px-2.5 py-1 text-[11px] font-medium rounded-md transition-colors duration-150
                  ${tab === "code" ? "bg-indigo-500 text-white" : "text-slate-500 hover:text-slate-200"}`}
              >
                <Code2 size={11} /> Code
              </button>
              <button
                onClick={() => setTab("preview")}
                className={`flex items-center gap-1.5 px-2.5 py-1 text-[11px] font-medium rounded-md transition-colors duration-150
                  ${tab === "preview" ? "bg-indigo-500 text-white" : "text-slate-500 hover:text-slate-200"}`}
              >
                <Eye size={11} /> Preview
              </button>
            </div>
          )}
        </div>
      </div>

      {/* File switching tabs (index.html, style.css etc) - Sirf Code view me dikhenge */}
      <AnimatePresence>
        {tab === "code" && (
          // Height animate ho rahi hai taaki smooth fold effect aaye
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.15 }}
            className="flex border-b border-white/[0.06] overflow-x-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden shrink-0"
          >
            {/* artifact.files map karke tab buttons banaye jaa rahe hain */}
            {artifact.files?.map((f, index) => (
              <button
                key={f.name}
                onClick={() => setActiveFile(index)} // File change karne pe state update hogi
                className={`px-4 py-2.5 text-[11px] font-medium whitespace-nowrap transition-colors duration-150 border-r border-white/[0.05] relative cursor-pointer bg-transparent
                  ${activeFile === index ? "text-indigo-400" : "text-slate-500 hover:text-slate-300"}`}
              >
                {f.name}
                {/* Active file indicator line (Niche blue line). layoutId "filetab" use karne se ye line ek tab se dusre tab me smoothly glide karegi */}
                {activeFile === index && (
                  <motion.div layoutId="filetab" className="absolute bottom-0 left-0 right-0 h-[2px] bg-indigo-500 rounded-t-full" />
                )}
              </button>
            ))}
          </motion.div>
        )}
      </AnimatePresence>

      {/* Main Content Area (Editor ya Preview) */}
      <div className="flex-1 overflow-hidden">
        {/* mode="wait" ka matlab: purana component hide ho jaye, uske baad hi naya component aaye */}
        <AnimatePresence mode="wait">
          {tab === "preview" && canPreview ? (
            
            // Web Preview Iframe
            <motion.div key="preview" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.15 }} className="w-full h-full">
              {/* sandbox="allow-scripts" ensures ki us iframe me script chale par baaki security restricted rahe (Interview security point) */}
              <iframe title="preview" sandbox="allow-scripts" srcDoc={previewDoc} className="w-full h-full bg-white" />
            </motion.div>
            
          ) : (
            
            // Code Editor (Monaco)
            <motion.div key={`code-${activeFile}`} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.15 }} className="w-full h-full">
              <Editor
                theme="vs-dark" // Dark theme set kiya
                language={detectLanguage(file?.name || "")} // Auto syntax highlighting (e.g., javascript, css)
                value={file?.content || ""} // Exact code text
                options={{ readOnly: true, minimap: { enabled: false }, fontSize: 13, wordWrap: "on", automaticLayout: true, scrollBeyondLastLine: false, padding: { top: 16 }, lineNumbers: "on", renderLineHighlight: "none" }}
              />
            </motion.div>
            
          )}
        </AnimatePresence>
      </div>
    </div>
  );

  // Main Return function jo UI mount karta hai
  return (
    <>
      {/* Mobile Floating Action Button (FAB). Jab lg: (large screen) hogi to ye hide (lg:hidden) ho jayega */}
      <button
        onClick={() => setMobileOpen(true)}
        className="lg:hidden fixed bottom-24 right-4 z-40 flex items-center gap-2 px-3.5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-[12px] font-medium shadow-lg shadow-indigo-500/20 border-none cursor-pointer transition-colors duration-150"
      >
        <FiCode size={13} /> View Code
      </button>

      {/* Mobile Slider / Drawer View */}
      <AnimatePresence>
        {mobileOpen && (
          <>
            {/* Backdrop: Peche dark background, click pe panel band ho jayega */}
            <motion.div key="mob-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.2 }} onClick={() => setMobileOpen(false)} className="lg:hidden fixed inset-0 z-50 bg-black/60 backdrop-blur-sm" />
            
            {/* Drawer: Right se slide-in hone wala panel */}
            <motion.div key="mob-drawer" initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} transition={{ duration: 0.25, ease: "easeInOut" }} className="lg:hidden fixed inset-y-0 right-0 z-50 w-[88vw] max-w-[420px] border-l border-white/[0.06] overflow-hidden">
              <PanelContent onClose={() => setMobileOpen(false)} />
            </motion.div>
          </>
        )}
      </AnimatePresence>

      {/* Desktop Panel View (Right side fixed panel) */}
      <AnimatePresence initial={false}>
        {!collapsed ? (
          
          // Panel Open hai
          // width clamp function se responsively set ho rahi hai: minimum 340px, default 38%, max 680px
          <motion.div key="open" initial={{ width: 0, opacity: 0 }} animate={{ width: "clamp(340px, 38%, 680px)", opacity: 1 }} exit={{ width: 0, opacity: 0 }} transition={{ duration: 0.22, ease: "easeInOut" }} className="hidden lg:flex h-full border-l border-white/[0.06] flex-col overflow-hidden shrink-0">
            <PanelContent />
          </motion.div>
          
        ) : (
          
          // Panel Collapsed (Band) hai, ek patli side strip dikhegi
          <motion.div key="collapsed" initial={{ width: 0, opacity: 0 }} animate={{ width: 48, opacity: 1 }} exit={{ width: 0, opacity: 0 }} transition={{ duration: 0.22, ease: "easeInOut" }} className="hidden lg:flex h-full border-l border-white/[0.06] bg-[#0d0f14] flex-col items-center py-4 gap-3 shrink-0">
            {/* Open Button: click karke panel bada hoga */}
            <button onClick={() => setCollapsed(false)} className="flex items-center justify-center w-8 h-8 rounded-lg text-slate-500 hover:text-slate-200 hover:bg-white/[0.05] transition-colors duration-150 bg-transparent border-none cursor-pointer">
              <PanelRightOpen size={15} />
            </button>
            
            {/* Vertical text display: writing-mode aur transform se text 90 degree rotate kiya hai (CSS Trick for interview) */}
            <div className="flex-1 flex items-center justify-center">
              <p className="text-[10px] font-medium text-slate-600 tracking-widest uppercase whitespace-nowrap" style={{ writingMode: "vertical-rl", transform: "rotate(180deg)" }}>
                {artifact.title}
              </p>
            </div>
          </motion.div>
          
        )}
      </AnimatePresence>
    </>
  );
}