// [What] Necessary libraries and modules import kar rahe hain.
// [Why] pptxgen: PowerPoint files dynamically generate karne ke liye.
// fs, path: File system aur paths handle karne ke liye (though yaha zyada use nahi hai).
// getModel, uploadToS3, getDownloadUrl, deductCredits, checkAgentLimit: Internal utilities jo LLM call karne, S3 me upload karne aur billing handle karne ke liye banaye gaye hain.
import pptxgen from "pptxgenjs";
import fs from "fs";
import path from "path";
import { getModel } from "../utils/model.js";
import { uploadToS3 } from "../utils/uploadToS3.js";
import { getDownloadUrl } from "../utils/getDownloadUrl.js";
import { deductCredits } from "../utils/deductCredits.js";
import { checkAgentLimit } from "../config/agentRateLimit.js";

// [What] Design Tokens (colors) ka ek object bana rahe hain (THEME).
// [Why] UI/UX consistency maintain karne ke liye. Jab bhi PPT me color use hoga, hardcode hex values ki jagah THEME object se reference lenge. Agar kal ko theme change karni ho, toh sirf yahan update karna padega.
const THEME = {
  dark:    "0F172A",   // cover / conclusion bg
  primary: "2563EB",   // accent color
  white:   "FFFFFF",
  offWhite:"F8FAFC",
  text:    "1E293B",
  muted:   "64748B",
  card:    "EFF6FF",   // light card bg
};

// [What] 'addCoverSlide' naam ka helper function bana rahe hain.
// [Why] Code reusability ke liye. Cover slide (pehle slide) ka design complex hota hai, isliye isko alag function me rakha gaya hai taaki main logic clean rahe.
function addCoverSlide(ppt, title, subtitle) {
  // [What] ppt object me ek nayi slide add kar rahe hain aur uska background set kar rahe hain.
  // [Why] Har slide ek blank canvas se shuru hoti hai. Dark theme cover page ko premium look deta hai.
  const slide = ppt.addSlide();
  slide.background = { color: THEME.dark };

  // [What] Top-right corner me ek large translucent circle (shape) add kar rahe hain.
  // [Why] Visual appeal badhane ke liye (decorative elements). Transparency se modern design aesthetic aata hai.
  slide.addShape(ppt.ShapeType.ellipse, {
    x: 10.5, y: -1.2, w: 4, h: 4,
    fill: { color: THEME.primary, transparency: 75 },
    line: { color: THEME.primary, transparency: 75 },
  });

  // [What] Bottom-left corner me ek chhota circle add kar rahe hain.
  // [Why] Design me balance create karne ke liye. Ye sab coordinates (x, y) inches me hote hain presentation slide me.
  slide.addShape(ppt.ShapeType.ellipse, {
    x: -0.8, y: 5.5, w: 2.5, h: 2.5,
    fill: { color: THEME.primary, transparency: 80 },
    line: { color: THEME.primary, transparency: 80 },
  });

  // [What] Slide par main Title add kar rahe hain.
  // [Why] User ka topic ya main heading show karne ke liye. Font size bada (36) aur bold rakha hai visual hierarchy ke liye.
  slide.addText(title, {
    x: 0.7, y: 2.0, w: 11.9, h: 1.2,
    fontSize: 36, bold: true, color: THEME.white,
    fontFace: "Calibri", align: "center",
  });

  // [What] Agar subtitle (tagline) provided hai toh usko title ke neeche add kar rahe hain.
  // [Why] Extra context dene ke liye. Ye optional parameter ho sakta hai isliye if condition check kar rahe hain.
  if (subtitle) {
    slide.addText(subtitle, {
      x: 0.7, y: 3.4, w: 11.9, h: 0.5,
      fontSize: 16, color: "94A3B8",
      fontFace: "Calibri", align: "center",
    });
  }

  // [What] Slide ke bottom me footer label ("Generated by AI-LUMA") daal rahe hain.
  // [Why] Branding aur watermark ke liye, taaki pata chale presentation kahan se bani hai.
  slide.addText("Generated by AI-LUMA", {
    x: 0.7, y: 6.7, w: 11.9, h: 0.25,
    fontSize: 10, color: "475569",
    fontFace: "Calibri", align: "center",
  });
}

// [What] 'addBulletSlide' helper function bana rahe hain.
// [Why] Ye common slide type hai jisme content bullet points me hota hai. Ye repeatedly use hoga, isliye function zaroori hai.
function addBulletSlide(ppt, slideIndex, title, bullets) {
  // [What] Nayi slide add kar rahe hain pichle background ke sath.
  // [Why] Content slides usually bright/white background wali hoti hain for readability.
  const slide = ppt.addSlide();
  slide.background = { color: THEME.white };

  // [What] Top-right corner me slide number badge bana rahe hain.
  // [Why] Professional presentations me slide numbers navigation and reference ke liye important hote hain.
  slide.addShape(ppt.ShapeType.ellipse, {
    x: 12.5, y: 0.15, w: 0.45, h: 0.45,
    fill: { color: THEME.primary },
    line: { color: THEME.primary },
  });
  slide.addText(`${slideIndex}`, {
    x: 12.5, y: 0.15, w: 0.45, h: 0.45,
    fontSize: 10, bold: true, color: THEME.white,
    fontFace: "Calibri", align: "center", valign: "middle",
  });

  // [What] Slide ka header/title add kar rahe hain.
  // [Why] Slide ka main topic define karne ke liye.
  slide.addText(title, {
    x: 0.6, y: 0.25, w: 11.6, h: 0.65,
    fontSize: 28, bold: true, color: THEME.primary,
    fontFace: "Calibri",
  });

  // [What] Title ke just neeche ek horizontal line (divider) add kar rahe hain.
  // [Why] Title ko main content se visually separate karne ke liye (aesthetic purpose).
  slide.addShape(ppt.ShapeType.line, {
    x: 0.6, y: 0.95, w: 11.8, h: 0,
    line: { color: "CBD5E1", width: 1.5 },
  });

  // [What] Bullet cards layout variables set kar rahe hain (height, startY, gap).
  // [Why] Har bullet point ko render karne se pehle positions calculate karni hoti hain taki overlap na ho.
  const cardH = 0.72;
  const startY = 1.15;
  const gap = 0.12;

  // [What] Bullets array pe loop lagakar maximum 6 points (using slice) render kar rahe hain.
  // [Why] 6 se jyada points ek slide me overcrowd ho jate hain aur layout bigad jata hai.
  bullets.slice(0, 6).forEach((txt, i) => {
    const y = startY + i * (cardH + gap);

    // [What] Har bullet ke peeche ek Rounded Rectangle shape bana rahe hain. Alternate colors use kar rahe hain (i % 2).
    // [Why] Simple text list ki jagah "card-style" list jyada modern lagti hai. Alternate colors padhne me asani (zebra striping) dete hain.
    slide.addShape(ppt.ShapeType.roundRect, {
      x: 0.6, y, w: 11.8, h: cardH,
      fill: { color: i % 2 === 0 ? THEME.card : THEME.offWhite },
      line: { color: "DBEAFE" },
      rectRadius: 0.08,
    });

    // [What] Text se pehle ek custom circular bullet dot add kar rahe hain.
    // [Why] Default bullets boring ho sakte hain, theme ke colors ke hisaab se custom shape draw karna better design deta hai.
    slide.addShape(ppt.ShapeType.ellipse, {
      x: 0.85, y: y + 0.24, w: 0.22, h: 0.22,
      fill: { color: THEME.primary },
      line: { color: THEME.primary },
    });

    // [What] Actual bullet text add kar rahe hain inside the rectangle.
    // [Why] Data ko display karne ke liye. Vertically center (valign) align rakha hai card ke andar.
    slide.addText(txt, {
      x: 1.2, y: y + 0.1, w: 10.9, h: cardH - 0.2,
      fontSize: 14, color: THEME.text,
      fontFace: "Calibri", valign: "middle",
    });
  });

  // [What] Footer me brand name add kar rahe hain.
  // [Why] Consistency ke liye har content slide me chhota watermark.
  slide.addText("AI-LUMA", {
    x: 0.6, y: 7.0, w: 2, h: 0.2,
    fontSize: 9, color: THEME.muted, fontFace: "Calibri",
  });
}

// [What] 'addStatSlide' helper function bana rahe hain.
// [Why] Ye special slide type hai jo data/numbers ko highlight karne ke liye use hota hai (metrics slide).
function addStatSlide(ppt, slideIndex, title, stats) {
  // [What] Dark background slide add kar rahe hain.
  // [Why] Stats/numbers dark background par pop karte hain aur user ka attention direct numerical values par jata hai.
  const slide = ppt.addSlide();
  slide.background = { color: THEME.dark };

  // [What] Slide Title add kar rahe hain.
  // [Why] Stats ka context dene ke liye (e.g., "Company Growth").
  slide.addText(title, {
    x: 0.6, y: 0.3, w: 12, h: 0.65,
    fontSize: 28, bold: true, color: THEME.white,
    fontFace: "Calibri",
  });
  
  // [What] Divider line draw kar rahe hain primary color me.
  // [Why] Title aur content separation ke liye.
  slide.addShape(ppt.ShapeType.line, {
    x: 0.6, y: 1.0, w: 11.8, h: 0,
    line: { color: THEME.primary, width: 2 },
  });

  // [What] Columns count calculate kar rahe hain (max 4 columns, warna stats ki length jitne).
  // [Why] Horizontal space limit hoti hai. Agar 3 items hain toh width dynamically divide hogi, par 4 se zyada stats permit nahi hain ui break hone se rokne k lie.
  const cols = stats.length <= 3 ? stats.length : 4;
  const cardW = 11.8 / cols;
  const startX = 0.6;

  // [What] Stats array pe loop chalakar maximum 4 cards draw kar rahe hain.
  // [Why] Har stat ko ek prominent 'card' me dikhana numbers ko easily readable banata hai dashboard style me.
  stats.slice(0, 4).forEach((s, i) => {
    const x = startX + i * cardW;
    
    // [What] Stat background card draw kar rahe hain.
    // [Why] Data ko frame karne ke liye.
    slide.addShape(ppt.ShapeType.roundRect, {
      x: x + 0.1, y: 1.5, w: cardW - 0.2, h: 3.8,
      fill: { color: "1E3A5F" },
      line: { color: THEME.primary, width: 1 },
      rectRadius: 0.12,
    });
    
    // [What] Bada number/value (jaise "42%") center me add kar rahe hain.
    // [Why] Value sabse important hai is slide type me, isliye fontSize 40 diya gaya hai.
    slide.addText(s.value, {
      x: x + 0.1, y: 1.9, w: cardW - 0.2, h: 1.5,
      fontSize: 40, bold: true, color: THEME.primary,
      fontFace: "Calibri", align: "center",
    });
    
    // [What] Label/description add kar rahe hain (jaise "Revenue Growth").
    // [Why] Number kya represent karta hai ye batane ke liye (subtext).
    slide.addText(s.label, {
      x: x + 0.1, y: 3.5, w: cardW - 0.2, h: 1.4,
      fontSize: 14, color: "CBD5E1",
      fontFace: "Calibri", align: "center",
    });
  });

  // [What] Standard branding footer daal rahe hain.
  // [Why] Slides me uniformity maintain karne ke liye.
  slide.addText("AI-LUMA", {
    x: 0.6, y: 7.0, w: 2, h: 0.2,
    fontSize: 9, color: THEME.muted, fontFace: "Calibri",
  });
}

// [What] 'addConclusionSlide' function bana rahe hain presentation end karne ke liye.
// [Why] Ye aakhri slide hogi jo summary provide karegi user ko.
function addConclusionSlide(ppt, title, points) {
  // [What] Nayi slide add kar rahe hain primary color background ke sath.
  // [Why] Solid primary color conclusion ko baaki slides se ekdum alag aur impactful banata hai.
  const slide = ppt.addSlide();
  slide.background = { color: THEME.primary };

  // [What] Background me ek badi transparent shape draw kar rahe hain.
  // [Why] Solid color thoda boring lagta hai, circles background me depth aur texture add karte hain (modern UI trait).
  slide.addShape(ppt.ShapeType.ellipse, {
    x: 10, y: 4.5, w: 5, h: 5,
    fill: { color: "1D4ED8", transparency: 60 },
    line: { color: "1D4ED8", transparency: 60 },
  });

  // [What] Main title (jaise "Thank You" ya "Summary") add kar rahe hain.
  // [Why] Conclusion ka topic define karne ke liye.
  slide.addText(title, {
    x: 0.7, y: 1.0, w: 9, h: 0.9,
    fontSize: 34, bold: true, color: THEME.white,
    fontFace: "Calibri",
  });
  
  // [What] Sub-heading "Key Takeaways" daal rahe hain.
  // [Why] User ko clearly batane ke liye ki yahan crucial summary points hain.
  slide.addText("Key Takeaways", {
    x: 0.7, y: 2.1, w: 9, h: 0.4,
    fontSize: 14, color: "BFDBFE",
    fontFace: "Calibri",
  });

  // [What] Final 4 points loop me render kar rahe hain white bullet dots ke sath.
  // [Why] Summary concise honi chahiye isliye max 4 restrict kiye gaye hain.
  points.slice(0, 4).forEach((p, i) => {
    slide.addShape(ppt.ShapeType.ellipse, {
      x: 0.7, y: 2.7 + i * 0.75, w: 0.3, h: 0.3,
      fill: { color: THEME.white },
      line: { color: THEME.white },
    });
    slide.addText(p, {
      x: 1.2, y: 2.65 + i * 0.75, w: 8.5, h: 0.55,
      fontSize: 15, color: THEME.white,
      fontFace: "Calibri",
    });
  });

  // [What] Center-aligned watermark.
  // [Why] End of presentation pe brand awareness ke liye.
  slide.addText("Generated by AI-LUMA", {
    x: 0.7, y: 7.0, w: 11.9, h: 0.2,
    fontSize: 9, color: "BFDBFE",
    fontFace: "Calibri", align: "center",
  });
}

// [What] LLM se mile text output ko structured object (JSON like) me convert karne ke liye function.
// [Why] LLM unstructured text generate karta hai. Code ko PPT banane ke liye structured arrays aur strings chahiye (jaise title kya hai, bullet points kya hain). ParseResponse us bridge ka kaam karta hai.
function parseResponse(content) {
  // [What] Ek base result structure initialize kar rahe hain.
  // [Why] Taaki agar regex match na ho ya parse fail ho, to code crash na kare blki default empty structure return kare.
  const result = {
    title: "",
    subtitle: "",
    slides: [],
  };

  // [What] Regex se TITLE line dhundh rahe hain.
  // [Why] System prompt ne AI ko "TITLE: xyz" format me respond karne ko bola hai. Ye regex us value ko extract karti hai.
  const titleMatch = content.match(/^TITLE:\s*(.+)/m);
  result.title = titleMatch?.[1]?.trim() || "Presentation";

  // [What] Regex se SUBTITLE extract kar rahe hain.
  // [Why] Cover page design ke liye required hai. Optional chain (?.) error se bachati hai agar subtitle nahi mila.
  const subtitleMatch = content.match(/^SUBTITLE:\s*(.+)/m);
  result.subtitle = subtitleMatch?.[1]?.trim() || "";

  // [What] Pure content ko "SLIDE:" keyword se split kar rahe hain.
  // [Why] Har slide ka chunk alag alag process kiya ja sake. .slice(1) ka use pehle header wale part (title/subtitle) ko hatane ke liye kiya hai.
  const rawSlides = content.split(/^SLIDE:/m).slice(1);

  // [What] Har ek raw slide text pe loop chala rahe hain.
  // [Why] Har text block ko analyze karke uski type aur content object form me dalna hai.
  rawSlides.forEach((raw) => {
    // [What] Slide text ko newline se todte hain aur empty lines filter karte hain.
    // [Why] Line-by-line processing easily karne ke liye.
    const lines = raw.split("\n").map(l => l.trim()).filter(Boolean);
    
    // [What] Aisi line dhundhte hain jo "Title:" ya "Type:" se start hoti ho.
    // [Why] Slide ka metadata extract karne ke liye (kya type hai, kya title hai).
    const titleLine = lines.find(l => l.startsWith("Title:"));
    const typeLine  = lines.find(l => l.startsWith("Type:"));

    // [What] Labels remove karke actual values store kar rahe hain (defaults fallback ke sath).
    // [Why] Agar AI proper format miss kar de, tabhi fallback defaults ("Slide", "bullets") system crash hone se bachate hain.
    const title = titleLine?.replace("Title:", "").trim() || "Slide";
    const type  = typeLine?.replace("Type:", "").trim().toLowerCase() || "bullets";

    // [What] Jo lines dash (-) se start ho rahi hain unko items (bullets) me store kar rahe hain.
    // [Why] Markdown lists extract karke frontend arrays me map karne ke liye.
    const items = lines
      .filter(l => l.startsWith("- "))
      .map(l => l.replace(/^-\s*/, "").trim());

    // [What] Stats type slides ke liye bullet points me pipe (|) split kar rahe hain.
    // [Why] Kyunki stats format "Label | Value" tha (e.g. "Users | 1M"). Ise key-value object {label, value} me convert karna zaruri hai.
    const stats = items.map(i => {
      const parts = i.split("|").map(p => p.trim());
      return parts.length === 2
        ? { label: parts[0], value: parts[1] }
        : { label: i, value: "" };
    });

    // [What] Ek complete slide object array me push kar rahe hain.
    // [Why] Result ready hone pe ye object easily forEach loop me daal kar PptxgenJS functions ko pass kiya jayega.
    result.slides.push({ title, type, items, stats });
  });

  // [What] Final structured data wapas bhej rahe hain.
  // [Why] Taaki calling function is object ka directly use kar sake PPT generate karne ke liye.
  return result;
}

// [What] Main asynchronous PPT Agent function export kar rahe hain.
// [Why] Ye main entry point hai jo state input lega, user ki limits check karega, AI se generate karwayega, PPT draw karke aws par upload karega.
export const pptAgent = async (state) => {
  try {
    // [What] User ka rate limit check kar rahe hain 'ppt' action ke liye.
    // [Why] Security aur business logic. Free users ko abuse se rokne ke liye ye check ensures ki unke paas allowed attempts bache hain. (Throws error agar limit cross ho jaye).
    await checkAgentLimit(
        state.userId,
        "ppt"
    );

    // [What] User ke balance se credits deduct kar rahe hain is premium PPT generation action ke liye.
    // [Why] Billing mechanism handle karne ke liye. Har generation ka cost hoga API aur S3 resources ki wajah se.
    await deductCredits(
        state.userId,
        "ppt"
    ); 

    // [What] "ppt" type ke liye configure kiya gaya LLM instance utha rahe hain.
    // [Why] Ye specific model ho sakta hai (e.g. gpt-4) jo formatted text aur strict templates jyada achhe se follow karta ho.
    const llm = getModel("ppt");

    // [What] LLM ko prompt bhej rahe hain presentation ka content likhne ke liye, ek strict output template ke sath.
    // [Why] "Few-shot prompting" ya strict system instructions di ja rahi hain. Bina is format ke, regex based parseResponse function fail ho jayega. Hum AI ko force kar rahe hain fixed DSL (Domain Specific Language) me reply karne ko.
    const aiResponse = await llm.invoke(` 
Create a professional PowerPoint presentation on the topic below.

Topic: ${state.prompt}

Output Rules:
- No markdown, no explanation, only the format below.
- Generate exactly 8 slides after the title.
- Slide types: bullets | stats | conclusion
  - bullets: 4-6 bullet points (most slides)
  - stats: 3-4 key metrics as "Label | Value" (use once for impact)
  - conclusion: 3-4 short takeaway points (last slide)

Format:

TITLE: Presentation Title
SUBTITLE: One-line tagline or description

SLIDE:
Type: bullets
Title: Introduction
- Point one
- Point two
- Point three
- Point four

SLIDE:
Type: stats
Title: Key Numbers
- Users Reached | 10M+
- Revenue Growth | 42%
- Countries | 30+

SLIDE:
Type: conclusion
Title: Conclusion
- Key takeaway one
- Key takeaway two
- Key takeaway three
`);

    // [What] Raw string response ko structured object me convert karte hain helper pass karke.
    // [Why] Kyunki javascript library (pptxgen) string samajh ke draw nahi karegi, usse functions ko call karne ke liye objects arrays chaiye (jaise arrays of bullets).
    const content = aiResponse.content.trim();
    const parsed  = parseResponse(content);

    // [What] Pptxgen class ka naya instance banate hain jisme default meta-data dalte hain.
    // [Why] Ye final presentation file (document object) banne ka process shuru karta hai, default 16:9 widescreen layout (LAYOUT_WIDE) ka set karta hai.
    const ppt = new pptxgen();
    ppt.layout  = "LAYOUT_WIDE";
    ppt.author  = "AI-LUMA";
    ppt.subject = state.prompt;
    ppt.title   = parsed.title;

    // [What] Cover slide helper ko call kar rahe hain extracted title/subtitle ke sath.
    // [Why] Presentation ka first impression build karne ke liye jo parse data se liya gaya hai.
    addCoverSlide(ppt, parsed.title, parsed.subtitle);

    // [What] Parse kiye hue slides ke array pe loop chalakar appropriate helper ko invoke kar rahe hain slide type ke basis par.
    // [Why] Dynamic PPT rendering engine! AI jaisa type define karega (stats, conclusion, default bullets), waisa function use hoga slide ko UI component ki tarah design karne ke liye.
    parsed.slides.forEach((slide, i) => {
      const num = i + 1; // 1-indexed slide number
      if (slide.type === "stats") {
        addStatSlide(ppt, num, slide.title, slide.stats);
      } else if (slide.type === "conclusion") {
        addConclusionSlide(ppt, slide.title, slide.items);
      } else {
        addBulletSlide(ppt, num, slide.title, slide.items);
      }
    });

    // [What] Final file name generate kar rahe hain unique timestamp ka use karke.
    // [Why] Taaki S3 bucket me duplicate files ka collision na ho aur data overwrite na ho.
    const fileName = `ppt-${Date.now()}.pptx`;

    // [What] PPT instance ko memory me "nodebuffer" binary format me write karte hain.
    // [Why] Node.js backend environment me disk IO directly karne ki jagah hum buffer banate hain jise turant cloud stream / AWS ko bheja ja sake.
    const buffer = await ppt.write({
      outputType: "nodebuffer"
    });

    // [What] Custom utility use karke S3 (Cloud Storage) me Buffer data upload kar rahe hain proper MIME type ke sath.
    // [Why] Presentation file user machine pe bhejne ke bajaye cloud me permanently/temporarily host hoti hai jahan se public URL banega.
    await uploadToS3(
      buffer,
      fileName,
      "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    );

    // [What] Uploaded file ke liye signed/temporary download link create karte hain jo 24 ghante (24*60*60s) tak valid rahega.
    // [Why] Security ke liye. S3 object ko public rakhne ki jagah presigned URL dete hain taaki unauthorized access na ho.
    const downloadUrl = await getDownloadUrl(
      fileName,
      24*60*60
    );

    // [What] Updated state return karte hain jisme final markdown response shamil hai.
    // [Why] RAG ya Bot framework final UI message me is state ko padhta hai aur download link render karta hai clickable button ki tarah.
    return {
      ...state,
      response: ` 
# Presentation Generated Successfully

 **${parsed.title}**

 [Download PPT](${downloadUrl})

 Link expires in 24 hours.
`
    };
  } catch (error) {
    // [What] Kisi bhi error ko catch karke gracefully handle karte hain aur error message return karte hain.
    // [Why] Agar API rate limit hua ya S3 fail hua toh process crash hone ke badle user friendly message dikhaye bot frontend par.
    console.log("PPT Agent Error:", error);
    return { ...state, response: "Failed to generate presentation." };
  }
};